apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-storage-volume-nfs-pvc
  namespace: openvas
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gvmd-storage-volume-nfs-pvc
  namespace: openvas
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openvas-storage-volume-nfs-pvc
  namespace: openvas
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-volume-nfs-pvc
  namespace: openvas
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi


---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gvmd-socket-volume-nfs-pvc
  namespace: openvas
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi


