apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ template "openvas.namespace" . }}

  annotations:
    # nginx.ingress.kubernetes.io/rewrite-target: /
  #   cert-manager.io/cluster-issuer: "letsencrypt"  # Reference the ClusterIssuer
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  #   acme.cert-manager.io/http01-edit-in-place: "true"

spec:
  ingressClassName: nginx  # Specify the Ingress class name
  tls:
  - hosts:
      - openvas-new.office.g-s.cloud # Replace with your domain
    secretName: tls-secret  # Name of the secret to hold the TLS certificate
  rules:
  - host: openvas-new.office.g-s.cloud  # Replace with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "openvas.fullname" . }}-service  # Replace with your service name
            port:
              number: 80  # Replace with your service's port